# Generated by Django 4.2.17 on 2025-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_id', models.IntegerField()),
                ('installation_name', models.CharField(max_length=100)),
                ('signal_uid', models.CharField(max_length=100)),
                ('signal_time', models.DateTimeField()),
                ('signal_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
