# Generated by Django 4.2.17 on 2025-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvMeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('production', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ppe', models.DecimalField(decimal_places=3, max_digits=10)),
                ('farm', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_2m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uv_index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direct_radiation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='PvData',
            new_name='PvTechnicalData',
        ),
    ]
