# Generated by Django 4.2.17 on 2025-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0002_pvmeasurementdata_rename_pvdata_pvtechnicaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='ppe',
            field=models.CharField(max_length=50),
        ),
    ]
