# Generated by Django 4.2.17 on 2025-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0003_alter_pvmeasurementdata_ppe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('production_forecast', models.DecimalField(decimal_places=3, max_digits=10)),
                ('farm', models.CharField(max_length=100)),
                ('ppe', models.CharField(max_length=50)),
            ],
        ),
    ]
