# Generated by Django 4.2.17 on 2025-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0005_forecastdatadayahead_delete_forecastdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdatadayahead',
            name='max_production',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='forecastdatadayahead',
            name='min_production',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
