# Generated by Django 4.2.17 on 2025-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0006_alter_forecastdatadayahead_max_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdatadayahead',
            name='production_forecast',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
