# Generated by Django 4.2.17 on 2025-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0007_alter_forecastdatadayahead_production_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeasurementdata',
            name='max_production',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pvmeasurementdata',
            name='min_production',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
