# Generated by Django 4.2.17 on 2025-01-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0008_pvmeasurementdata_max_production_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pvmeasurementdata',
            unique_together={('timestamp', 'ppe')},
        ),
    ]
