# Generated by Django 4.2.17 on 2025-01-25 17:56

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0009_alter_pvmeasurementdata_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pvtechnicaldata',
            managers=[
                ('unique_data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pvtechnicaldata',
            name='signal_time',
        ),
        migrations.AddField(
            model_name='pvtechnicaldata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='direct_radiation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='farm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='ppe',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='production',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='temperature_2m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='uv_index',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
