# Generated by Django 4.2.17 on 2025-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0010_alter_pvtechnicaldata_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvtechnicaldata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
