# Generated by Django 4.2.17 on 2025-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0011_alter_pvtechnicaldata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmeasurementdata',
            name='production',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
