# Generated by Django 4.2.17 on 2025-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0012_alter_pvmeasurementdata_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeasurementdata',
            name='direct_radiation_forecast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
