# Generated by Django 4.2.17 on 2025-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0013_pvmeasurementdata_direct_radiation_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeasurementdata',
            name='global_tilted_irradiance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pvmeasurementdata',
            name='global_tilted_irradiance_forecast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
